### PR TITLE
Adjusted @functions to @code.

### PR DESCRIPTION
**Pull request by SeppPenner**
The call to `@functions` should be changed to `@code` following https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

> Rename `@functions` to `@code`

### CODE REVIEW

**Comment by Joelius300** [comment]
Since this needed to be done for more than just this one chart, I added it in https://github.com/Joelius300/ChartJSBlazor/pull/60. I think this is acceptable since it's a change that is connected to updating the packages (although we could've done it earlier) and also because it only affects the samples.

**Comment by SeppPenner** [comment]
Yes, that's okay.

**Comment by Joelius300** [comment]
Very sorry, I missed it in the readme as well.. I'll do that quickly, you don't need to do anything @SeppPenner :)

**Comment by SeppPenner** [comment]
Haha okay. This always happens to me as well...

**Pull request closed without merging**
