### PR TITLE
Added polar area example.

### PR DESCRIPTION
**Pull request by SeppPenner**

### CODE REVIEW

**Review by Joelius300 — COMMENTED** [review]
I have not had the possibility to check it yet (cannot run it from this PC) but I think I can assume that you checked that it works (e.g. clicking the labels, animation etc), right?

By the way, I think you should try to be consistent with the use of `AddRange`. First you use an array and then a list. Just use array in both, it's also less expensive :)

Something else I noticed. You used `oi-graph` as icon. I didn't know this existed but I think this would fit the line chart samples better than the current `oi-bar-chart` so we should change that (doesn't really belong in this PR but it's so small I don't mind). Also are you sure that `oi-graph` fits the polar-area-chart the best?  
You can choose from:

- oi-graph
- oi-bar-chart
- oi-pie-chart

I think as a general rule we should use a default if there isn't anything fitting. The default was `oi-bar-chart` but now I think it's better to set `oi-graph` as default and only use `oi-bar-chart` where it fits. For the polar-area-chart using the default is probably the way to go. I don't think that it'd make sense using pie-chart there, what do you think?

**Comment by SeppPenner** [comment]
> I have not had the possibility to check it yet (cannot run it from this PC) but I think I can assume that you checked that it works (e.g. clicking the labels, animation etc), right?

Yes, it's tested.

> By the way, I think you should try to be consistent with the use of AddRange. First you use an array and then a list. Just use array in both, it's also less expensive :)

~~That was a mistake I guess.~~ I will correct this in the other examples as well, because there it's the same... (I just copied the pie chart example and adjusted it 😄).

You're right. I was searching for another icon that fits, but the bar chart as default is a good idea. And yes, the line chart should use the graph icon. Makes more sense.

**Comment by SeppPenner** [comment]
It's done :)

**Comment by Joelius300** [comment]
Looks good. Will be merged once I get to test it :)

**Comment by Joelius300** [comment]
I pushed a commit to use `new double[] { 4, 5, 6, 7 }` instead of `new[] { 4.0, 5.0, 6.0 7.0 }` because I like it more this way and as far as I'm concerned it's a bit more 'correct'. I will merge this now.

**Pull request merged**
