### PR TITLE
Contributing and issue templates

### LINKED ISSUE #24: Create a (short) Contributing section in README.md and add a CONTRIBUTING.md file
As this project isn't just one person doing it anymore we should create contributing guidelines including but not limited to

- The contribution process (how to contribute)
- A short explanation of the project architecture and the CI/CD pipeline
- A short summary of code style and conventions

Plus anything more you can think of

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/24.

### CODE REVIEW

**Comment by Joelius300** [comment]
Looks very good.  

Can you add a mention to the XML-guidelines? Or should we do that once https://github.com/Joelius300/ChartJSBlazor/issues/22 is done?

**Comment by SeppPenner** [comment]
I can add this now already.

**Comment by Joelius300** [comment]
Do you want to do https://github.com/Joelius300/ChartJSBlazor/issues/22 or should I do it? I just wanted to start but now I'm not sure if you've already started with it..

**Comment by SeppPenner** [comment]
@Joelius300 If you want to start, I would merge this pull request (Well, you would merge it actually) and you can do #22 afterwards. I haven't started yet.

**Pull request merged**
