### PR TITLE
Hotfix/missing tooltips in option class 89

### LINKED ISSUE #89: Missing Tooltips in Option Class
### Describe your question
First of all, this is an awsome library. Today i wanted to set the Tooltips options (i wanted to turn them off) and i realized, that this option is not in the PieOptions class for example or in the base class. I was wondering if this is as it should be?

### Which Blazor project type is your question related to?
- Server-Side

### Which charts is this question related to?
PieChart

Thanks in advance,
r Michael

### PR DESCRIPTION
**Pull request by TomaszGrzmilas**
Fix #89 

Add:
FontStyle : StringEnum
TooltipPosition : StringEnum
Tooltips properties

### CODE REVIEW

**Comment by Joelius300** [comment]
Already looks pretty good :)

I saw that you mentioned the enum for the property you added similar to how it's done for colors. I think you should remove those mentions again because it's obvious what values are possible from the type. For colors we mention the ColorUtil because it's of type string so they might not know how to approach that. For enums that isn't really necessary imo.  
It's not a bad thing in general but because we didn't do it like this anywhere else and I don't see it as necessary, I think you should remove those remarks.

I also see that you added the FontStyle enum. This is already done in #87. I expect #87 to be merged before this so I will remove the file here once I get to merge this but for the moment you can leave that, I'll handle it later.

**Comment by TomaszGrzmilas** [comment]
Sorry for the mess in commit history. :/

**Review by Joelius300 — CHANGES_REQUESTED** [review]
Looks good but I'm not quite satisfied with the summaries yet.

In `TooltipPosition` you should use the pattern "If <see cref="TooltipPosition.Average"/> is set, the tooltips will be placed...". Similarly for the other option of course. You can look at #87 for reference. 

Also in `Tooltips` itself, you should use the "Gets or sets.." pattern. A good reference is [`PieOptions`](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJS/PieChart/PieOptions.cs).  
Also keep in mind to use the pattern "Gets or sets the value indicating.."  for boolean properties.

**Comment by TomaszGrzmilas** [comment]
> Looks good but I'm not quite satisfied with the summaries yet.
> 
> In `TooltipPosition` you should use the pattern "If is set, the tooltips will be placed...". Similarly for the other option of course. You can look at #87 for reference.
> 
> Also in `Tooltips` itself, you should use the "Gets or sets.." pattern. A good reference is [`PieOptions`](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJS/PieChart/PieOptions.cs).
> Also keep in mind to use the pattern "Gets or sets the value indicating.." for boolean properties.

Sorry, I took pattern from existing properties in the tooltip class (Mode, Intersect), didn't saw how it's done somewhere else.

BR

**Review by Joelius300 — CHANGES_REQUESTED** [review]
I have left a few comments. It's almost done :)

Sorry for being so picky about the summaries. I want to pay a lot of attention to those since that's what lets the consumer know how to use it if they don't know chart.js that well.

**Comment by TomaszGrzmilas** [comment]
No problem, I will know, next time what are the patterns for comments and what to looks out :)

**Comment by Joelius300** [comment]
@TomaszGrzmilas Could you add me as a collaborator in your forked repository so I can resolve the conflict and do a final touch before merging your pull request? You can also check the box _Allow edits from maintainers_ for this PR if you don't want to add me as a collaborator in your repo.

**Comment by SeppPenner** [comment]
@TomaszGrzmilas: I wanted to push things faster and opened https://github.com/Joelius300/ChartJSBlazor/pull/99 for that. @Joelius300 explained to me that this was rude and I can understand that point of view. I just wanted to apologize for this.

**Comment by Joelius300** [comment]
It's not that important but I want to clear this up: I will work on this pull request this evening and if I don't have write-access to it until then, I will do it with a separate branch. Opening #99 is a confusing decision in my opinion because it discards the commit history and adds a duplicate PR which also kind of invalidates this one. It's also not really faster because I cannot work on it until the evening anyway and opening that other branch would be a matter of seconds.  
From my point of view, #99 was not appropriate and thus I intervened.

It should be all good now and we can continue working as normal :)

**Comment by TomaszGrzmilas** [comment]
@Joelius300 
Hi, just added you

**Comment by TomaszGrzmilas** [comment]
> @TomaszGrzmilas: I wanted to push things faster and opened #99 for that. @Joelius300 explained to me that this was rude and I can understand that point of view. I just wanted to apologize for this.

@SeppPenner No need to apologize me :) I'm glad that I can support this repo.

**Review by Joelius300 — APPROVED** [review]
It should be all good now. I have found many more issues outside of this PR (as always) that need to be corrected in future patches and I have put them in my personal backlog. They will be tracked in the original repo of marius where all future development will take place.

**Pull request merged**
