### PR TITLE
Updating readme, knownissues link and clientside blazor

### PR DESCRIPTION
**Pull request by patrickhacens**
upading read me with info from issue #93

### CODE REVIEW

**Comment by SeppPenner** [comment]
Looks good for me. Some small changes from my side:

* I would close all sentences with a dot
* Describe what `PROBLEMATIC_COMPONENT` stands for and provide an example, e.g. "PROBLEMATIC_COMPONENT here means a specific chart component like `ChartJsLineChart`"
* "For more information, check out our known issues page" (With the link of course as you already have it)

Before you change something here, please wait for @Joelius300 remarks, too. He might have some more ideas.

And thank you for the pull request. I wanted to do that but didn't have the time yet :D

**Comment by Joelius300** [comment]
I approve the comments of @SeppPenner. I can only emphasize that the example for the `ReferenceConverter` stuff has to be very clear.

**Comment by SeppPenner** [comment]
@Joelius300 I integrated this into https://github.com/Joelius300/ChartJSBlazor/pull/98 (Because both are changes in the readme) to get this done.

**Comment by Joelius300** [comment]
Since there were a few changes for the readme that could be done together, this pull request is now unnecessary since your work has been reused in https://github.com/Joelius300/ChartJSBlazor/pull/98 :)

**Pull request closed without merging**
