### PR TITLE
Updated nuget packages to NetCore 3.0 release.

### LINKED ISSUE #91: Update to .NET Core 3.0 release
# Rejoice, for .NET Core 3.0 has released

.NET Core 3.0 released a few days ago, I think we should update to it. This should be very easy as going from Preview 9 to release was primarily bug fixes https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/91.

### CODE REVIEW

**Comment by Joelius300** [comment]
Looks fine. I'm assuming you tested everything and it still works as expected, correct?

Since I'm still writing this from the beach, I think I will wait to merge this (just like all the other PRs) and do it as soon as I have time to test everything.

**Comment by SeppPenner** [comment]
Yes, it's tested and works like before.

**Comment by SeppPenner** [comment]
Does `netstandard2.1` work for Blazor? The last time I tried with the preview, it didn't :D

**Comment by Joelius300** [comment]
Hah I knew there was something :)

I think server-side (our sample) works fine but client-side might not work since the mono runtime doesn't support 2.1 yet. I will test this.

**Pull request merged**
