### PR TITLE
Reworked bar chart.

### PR DESCRIPTION
**Pull request by SeppPenner**
New try now without the git noise.

### CODE REVIEW

**Comment by SeppPenner** [comment]
> In BarThickness you should have a static method Absolute(double thickness) instead of a public constructor. Also adding an implicit conversion operator from double to BarThickness would be nice.

This is already done.

> Also what doesn't work with the sample? Are there errors or does it just not work?

The configuration is somehow strange (Because of the MixableDataset stuff). --> I didn't get it to work properly with the labels and data items.

* `config.Data.Labels` cannot be resolved
* `barSet.Data` is of type `IReadOnlyCollection` and doesn't support `AddRange`
* `BarDataset` needs a type parameter of a class type

**Comment by SeppPenner** [comment]
Nevermind the organization name by the way. It was the easiest thing to clone the repository again and just add the adjusted files again. (I didn't want to do it with my personal fork because the guys from Microsoft still need the static assets branch).

**Review by Joelius300 — CHANGES_REQUESTED** [review]
Why is `YAxes` an array while `XAxes` is a list in `BarScales`?

Please use `=> new BarThickness(thickness);` for `Absolute` as well. No need for the body there.

I will have to look into the dataset stuff. I don't have enought time right now.

> config.Data.Labels cannot be resolved

Well yeah.. you removed them [here](https://github.com/Joelius300/ChartJSBlazor/pull/86/commits/51626b4502517bd03b013795c666774d9b809077#diff-65c5b5df9869770c4ca67b16567ddea5L8)

> barSet.Data is of type IReadOnlyCollection and doesn't support AddRange

You don't call `barSet.Data.AddRange`, you call `barSet.AddRange`. `Data` has to be readonly for the covariance to work.

> BarDataset needs a type parameter of a class type

This is correct. This is required for covariance. The mention of the wrappers is already there.

**Comment by SeppPenner** [comment]
> Why is YAxes an array while XAxes is a list in BarScales?

You're right, I missed that one.

> Please use => new BarThickness(thickness); for Absolute as well. No need for the body there.

Done.

> Well yeah.. you removed them here.

I'm now able to get the bar chart working. Do we need another example for one with time and `double`  value? I have created one with `double` values on both axes now.

image

**Comment by Joelius300** [comment]
Please split up your commits. Having only one commit called `Fixed all current issues` should raise a red flag for you.

You fixed the three things I wanted you to:

- `=>` expression for absolute
- Add `Labels` back
- Make `YAxes` from `BarAxis[]` to `List<BarAxis>`

However you also created a really weird example. First of all, you don't define a new class for the datatype. If you want something with x and y you can just use [`Point`](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJS/Common/Point.cs).  
Now if you read through the [chartjs docs page](https://www.chartjs.org/docs/latest/charts/bar.html#data-structure) you can see that you can either specify an array of numbers (which will be indexed with together with the labels) or you can use a `TimeAxis` as scale and then you can use a `TimeTupel<double>`. The labels would be ignored in the latter case.

Currently it's not possible to use `TimeAxis` because the axes are fixed on `BarAxis`. This is a bit more complicated and I can look into that when I get time. For now please remove that example data class and use a `BarDataset<DoubleWrapper>`. You can use the `Wrap()` extension method once you have your collection of doubles so you can put them in the dataset.  
Also you should probably specify the scales explicitly. I don't understand why there is both x and y (maybe for horizontal?) but you should probably specify a yAxis explicitly. You should also look at the [samples](https://www.chartjs.org/samples/latest/), I don't fully understand how the bar-axes work yet.

> I have created one with double values on both axes now.

No, you have not. The double on the x axis is just swallowed. It uses the label. For the _n_ th value in `Data` it displays the _n_ th label from `Labels`.

> Do we need another example for one with time and double value?

We can't currently because it's not yet possible to use `TimeAxis` as scale.

**Comment by SeppPenner** [comment]
> Please split up your commits. Having only one commit called Fixed all current issues should raise a red flag for you.

The original commits were split. This was because of the git issue I had. Obviously, I didn't want to do all the changes again and just copied the changed files from one directory to another.

> However you also created a really weird example. First of all, you don't define a new class for the datatype. If you want something with x and y you can just use Point.

I didn't find that one.


The rest is done.

Tasks:

* Check this time axis thing
* Provide a new example for the time axis once it's possible

**Comment by SeppPenner** [comment]
@Joelius300 Do you want to bring this feature to the repository before or after the merge?

**Comment by Joelius300** [comment]
I have found out a few things. `BarChart` actually accepts all `CartesianAxes` ([source](https://www.chartjs.org/docs/latest/axes/cartesian/#common-configuration), the wording [here](https://www.chartjs.org/docs/latest/charts/bar.html#dataset-properties) seems a bit off) which means the `TimeAxis` problem is solved. This also means `BarDataset` should derive from `CartesianAxis`. `BaseBarDataset` also seems unnecessary now.

There are also a few conflicts with the master branch which need to be addressed first. I will work on this and hopefully get it done fast enough to merge it here. Otherwise we'll just do it again in the original repo (which would also result in less steps of course).

**Comment by SeppPenner** [comment]
Ok, sure. Feel free to change this :D

**Review by Joelius300 — APPROVED** [review]
I think this is all done now. I will merge this and focus on the migration. The issues etc will be transferred. Same goes for my backlog. 

Thank you @SeppPenner for the PR :)

**Pull request merged**
