### PR TITLE
Updated readme: NetCore and VS information, added disclaimer for the UncaughtReference error.

### LINKED ISSUE #93: Chart not drawn on client-side blazor in .netcore 3.0
### Describe the bug
Chart on client-side is not rendered and the following error is shown on the browser console
>WASM: ﻿Error while setting up chart: Constructor on type 'System.ComponentModel.ReferenceConverter' not found.

### Which Blazor project type is your bug related to?
- Client-Side

### Which charts does this bug apply to?
Line Chart but i had not the time to test on them all

### To Reproduce
1. Using this version of ChartJSBlazor '0.10.3-preview'.
2. Using .net core 3.0.0
3. Run a copy of the LineLinearExample from commit 80ce21705c58c76812d3adab4100dd29a700e8f3.

### Expected behavior
The chart to be drawn unto the screen

### Correction found
Searching a bit I found a solution on this link https://github.com/JamesNK/Newtonsoft.Json/issues/2020, it seems to be a problem with `Newtonsoft.Json` but I'm not sure if it should be corrected by them

```csharp
//the following line on the page/component that renders the chart corrected to the spected behavior
@using System.ComponentModel;
private ReferenceConverter ReferenceConverter = new ReferenceConverter(typeof(ChartJsLineChart));
```

### LINKED ISSUE #94: Uncaught ReferenceError
I've probably missed a step somewhere but when I run using Blazor (server side) latest

I get 

: Blazor is not defined     at ChartJsInterop.js:5

when I check the console window.  Any ideas?

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/94, fixes https://github.com/Joelius300/ChartJSBlazor/issues/93, makes https://github.com/Joelius300/ChartJSBlazor/pull/95 redundant.

This pull request updates the information regarding requirements for Visual Studio and .NetCore and adds additional information on two commonly known issues: The `Chart not drawn on client-side blazor in .netcore 3.0` from https://github.com/Joelius300/ChartJSBlazor/issues/93 and the `Uncaught reference error` from https://github.com/Joelius300/ChartJSBlazor/issues/94.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/93, makes https://github.com/Joelius300/ChartJSBlazor/pull/95 redundant.

**Comment by Joelius300** [comment]
What do we want to do about the prerequisites? For this repo you don't need the preview for Visual Studio since we don't have client-side blazor in it. For the original repo you will need the preview AND you'll need .NET Core 3 preview 9 as well since client-side blazor is not available in .NET Core 3.0.

I think we should adjust it to how it's currently (.NET Core 3.0 and Visual Studio 2019 16.3) but keep the other things I said in mind for the original repo.

**Comment by Joelius300** [comment]
Do you approve these changes to your PR @SeppPenner?

**Comment by SeppPenner** [comment]
> I think we should adjust it to how it's currently (.NET Core 3.0 and Visual Studio 2019 16.3) but keep the other things I said in mind for the original repo.

Yeah, that's a good idea.

**Comment by Joelius300** [comment]
I guess that's an approval :) I'll merge it.

**Comment by Joelius300** [comment]
The commit history of this PR is pretty bad for some reason. Maybe we should've organized it first but since it was squashed it's not a problem in master. I will leave it like this.

**Comment by SeppPenner** [comment]
> The commit history of this PR is pretty bad for some reason.

I have seen that, but I have actually no idea why...

**Pull request merged**
