### PR TITLE
Added readme from original project.

### PR DESCRIPTION
**Pull request by SeppPenner**
Check discussion under https://github.com/Joelius300/ChartJSBlazor/issues/3

### CODE REVIEW

**Comment by Joelius300** [comment]
There are a few things that I would say are not correct anymore.   

First of all we're operating on the newest preview so "DotNetCore 2.1.402" is not enough and neither is "VS 15.8". You need ".net core 3 preview6" and the preview version of VS 19.  

The part with "AddStaticResourcesToWebRootPath" is currently correct but will be removed soon. This will be unnecessary if we add a "wwwroot" folder to the library with the contents in it (just rename dist to wwwroot). This is a new preview feature.   

In addition to the script tag for the js-interop, it is also required to include the CSS to make the charts responsive. Currently there is some ugly js code that includes the CSS for you. As far as I'm concerned, that's bad and should be removed.  

The code for the pie chart is not up to date.   
 - First of all there is no more "ref" attribute. It's now "@ref". 
 - Because these charts arent supposed to be static anyway I don't want to encourage that the data is initialized alongside with the rest of the config. `Data` only has a getter now and you need to manually add the dataset. Currently I have not reworked any other charts apart from the LineChart. The plan is to have every chart config behave like the LineChartConfig currently does. This means that you cannot initialize the Data part of the config like that. 
 - `PieChartOptions.Text` was wrong and has been removed to correctly reflect the Title object. See [the docs](https://www.chartjs.org/docs/latest/configuration/title.html).
 - There is no `PieChartAnimation` since it's the same as `DoughnutAnimation`. These might be renamed later to make them more clear.

Here's the updated version that gives the same result:
```
@using ChartJs.Blazor.Charts
@using ChartJs.Blazor.ChartJS.PieChart
@using ChartJs.Blazor.ChartJS.Common.Properties

<h1>Pie Chart</h1>

<ChartJsPieChart @ref="_pieChartJs" Config="@_config" Width="600" Height="300" />

@code {
private PieChartConfig _config;
private ChartJsPieChart _pieChartJs;

protected override void OnInit()
{
    _config = new PieChartConfig
    {
        CanvasId = "myFirstPieChart",
        Options = new PieChartOptions
        {
            Title = new OptionsTitle
            {
                Display = true,
                Text = "Sample chart from Blazor"
            },
            Responsive = true,
            Animation = new DoughnutAnimation
            {
                AnimateRotate = true,
                AnimateScale = true
            }
        }
    };

    _config.Data.Labels = new List<string> { "A", "B", "C", "D" };

    var pieSet = new PieChartDataset
    {
        BackgroundColor = new[] { "#ff6384", "#55ee84", "#4463ff", "#efefef" },
        Data = new List<int> { 4, 5, 6, 7 },                // this will be removed and shouldn't be possible
        Label = "Light Red",
        BorderWidth = 0,
        HoverBackgroundColor = new[] { "#f06384" },
        HoverBorderColor = new[] { "#f06384" },
        HoverBorderWidth = new[] { 1 },
        BorderColor = "#ffffff",
    };

    _config.Data.Datasets = new List<PieChartDataset>();    // this will be removed and shouldn't be possible
    _config.Data.Datasets.Add(pieSet);
}
}
```

**Comment by Joelius300** [comment]
I've noticed some other things that aren't correct anymore.  

- It's not `.cshtml` anymore but `.razor`
- The imports belong in `_Host.cshtml`
- The imports are not on the newest version

Here are two versions that are working (don't forget the required scripts for blazor itself):  

This version manually included moment.js so that you have the locales.
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"
        integrity="sha256-AdQN98MVZs44Eq2yTwtoKufhnU+uZ7v2kXnD5vqzZVo="
        crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script src="~/ChartJs.Blazor/ChartJsInterop.js" type="text/javascript" language="javascript"></script>
```

This version includes the bundle version of chartJs which contains momentJs, just without locales.
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script> <!--Contains moment.js for time axis-->
<script src="~/ChartJs.Blazor/ChartJsInterop.js" type="text/javascript" language="javascript"></script>
```

**Comment by SeppPenner** [comment]
Ok, I will check this and change the requested stuff.

**Comment by SeppPenner** [comment]
@Joelius300 Please review my changes again, it should now look better ;)

**Pull request merged**
