### PR TITLE
Added mentions for color util for all occurences.

### LINKED ISSUE #42: Mention ColorUtil in PieChartDataset.BackgroundColor (and potentially other places it was forgotten)
From https://github.com/Joelius300/ChartJSBlazor/pull/23:

We need to mention ColorUtil in PieChartDataset.BackgroundColor (and potentially other places it was forgotten).

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/42.

### CODE REVIEW

**Review by Joelius300 — APPROVED** [review]
Looks good. I see some issues but those are completely unrelated to this change so it's safe to merge.

**Comment by SeppPenner** [comment]
@Joelius300 I haven't updated the documentation and that stuff. I just wanted to update the documentation for the `ColorUtils` so that we don't miss this in the future (and get rid of some `low hanging fruits`).

**Comment by Joelius300** [comment]
I don't think we need documentation changes for this. A small thing you should get in the habit of is always building the solution when you've changed anything.  

For code changes it's important to know if the code compiles.  
For docs changes (xml) it's also important since the [ChartJs.Blazor.xml](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJs.Blazor.xml) won't get updated otherwise. This is setup on project basis (see [here](https://github.com/Joelius300/ChartJSBlazor/blob/master/ChartJs.Blazor/ChartJs.Blazor.csproj#L45)) so it should work on build for you too.

**Comment by SeppPenner** [comment]
You're right. I haven't used this for the small documentation changes here because I didn't think of the generated XML doc...

**Pull request merged**
