### PR TITLE
Updated to preview9.

### LINKED ISSUE #74: Update to NetCore preview9.
This should be quite easy, I guess: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/.

I will provide a pull request for this soon.

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/74.

@Joelius300: I have tested it and all charts are shown, all buttons add some new data.

### CODE REVIEW

**Comment by SeppPenner** [comment]
I have updated the wiki and readme as wel (I hope, I didn't forget anything there...).

**Comment by Joelius300** [comment]
I'm confused.. isn't this the same as https://github.com/Joelius300/ChartJSBlazor/pull/73? You should have added commits there if necessary.. Or do you not have permission for that?

**Comment by SeppPenner** [comment]
I guess, that happens, when people don't use Github with all its features... If you added an issue before and something like `Fixes #74`, I would have seen your pull request (https://github.com/Joelius300/ChartJSBlazor/pull/73) already @cbovar...

**Comment by SeppPenner** [comment]
> I'm confused.. isn't this the same as #73? You should have added commits there if necessary.. Or do you not have permission for that?

I guess it is. But no, I don't believe I can change things there.

**Pull request merged**
