### PR TITLE
Special enums

### PR DESCRIPTION
**Pull request by SeppPenner**
Special enums will be done here.

The first is `BorderAlign` --> StringEnum.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/9, Fixes https://github.com/Joelius300/ChartJSBlazor/issues/41.

**Comment by SeppPenner** [comment]
This is done now. I have to check the issue with the commits...

**Comment by Joelius300** [comment]
Just like with your other branch, the commit history is broken. We cannot merge this. You might be able to resolve this using cherry-pick. Hardreset on my master on some new branch, cherry-pick the commits from here and keep working there. Hardreset your master on my master then and merge the new branch to your master. Should work but again, no git expert here :)

Also to the actual commits:

- As mentioned in the other PR, summaries for private constructors aren't really necessary (you don't need to remove them since they're done now).
- There's a missing space in front of : in `BorderCapStyle`.
- You should move the infos from the constructor summary in `CubicInterpolationMode` to the class summary.
- "As per documentation here.." makes sense for the enums themself but doesn't add value if it's put in the property-summary.
- The summaries of many properties need to be rewritten or adjusted. Sometimes there's a mention of 'center' but now we should reference `Enum.Center' using a `<see/>`-tag. As mentioned above, it doesn't make sense anymore to reference where these values are defined outside the library since we now have an enum. Just reference the enum and it's values where necessary.
- Since string enums can be null, I don't think we should set a default value and just let chart.js pick the appropriate one. Example of this is in `PointLabels.FontStyle`. Only use a default value if the default isn't null. 

I have not checked the actual values of the enums, I'll do that later.

**Comment by SeppPenner** [comment]
Is now done in https://github.com/Joelius300/ChartJSBlazor/pull/87.

**Pull request closed without merging**
