### PR TITLE
Moved changelog to extra file.

### LINKED ISSUE #35: Move changelog to extra file
I would move the changelog to an extra file to avoid bloating the readme file.

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/35.

### CODE REVIEW

**Comment by SeppPenner** [comment]
@Joelius300 This one should be easy to merge (As far as you don't have any concerns).

**Comment by Joelius300** [comment]
Looks good. Can you add the link to the readme as well?

**Comment by SeppPenner** [comment]
> Looks good. Can you add the link to the readme as well?

Er, I don't understand that. The link to the changelog is already there: https://github.com/SeppPenner/ChartJSBlazor/blob/move-changelog/README.md#latest-changes

> The full changelog can be found here

**Comment by Joelius300** [comment]
No idea how I missed that, maybe I messed up between my many tabs.  

It's all good, thanks.

**Comment by SeppPenner** [comment]
@Joelius300 Maybe because all the issues and pull requests here are getting too crazy :D

**Pull request merged**
