### PR TITLE
Added selection to which chart this applies to in issue templates.

### LINKED ISSUE #66: Add selection to which chart this applies to in issue templates
For the issue templates we should add "which charts does this bug/feature request apply to" or something like that instead of just "which version (client vs server)".

For bugs we need to have both ("which chart" and "which version"), for feature requests it will always affect both versions (client & server) so we only need "which chart" there.  

It should say something like "Which chart is your feature request related to?" (same for bug ofc) with a comment stating that you should list the charts or write "All".

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/Joelius300/ChartJSBlazor/issues/66.

@Joelius300 Is this sufficient? Please provide me some feedback if there is something else that needs to be done.

### CODE REVIEW

**Comment by Joelius300** [comment]
Seems good but actually I think it's sufficient if you tell them to list which charts it applies to, we don't need to mention which charts exist. For the server-side/client-side this makes sense because it's only 2 and also users might not know what possiblities there are.

I would suggest you to remove the list of charts and just say something like "Please list the charts you experienced this bug with." and "Please list the charts this feature request applies to." To both we should add "If it applies to all of them, just write 'all charts'".

**Comment by SeppPenner** [comment]
Okay, I can change that.

**Comment by SeppPenner** [comment]
I have added the `labels` as well (I hope, it works like that, we might need to test that). --> If you open up a new bug, the `bug` label should be added automatically now. (For the others as well).

**Comment by SeppPenner** [comment]
Ok, I have tested the generation of labels: https://github.com/Joelius300/ChartJSBlazor/issues/72. It seems to work.

**Pull request merged**
