### PR TITLE
Reworked pie and doughnut chart (RIP).

### LINKED ISSUE #20: Data should be a List<double>
From the line chart example in the readme:

```csharp
Data = new List<int> { 4, 5, 6, 7 },
```

It should be (and it is in Chart.Js) possible to add double / float values to the chart data as well. So, in my opinion `Data` should be of type `List<double>`.

### PR DESCRIPTION
**Pull request by SeppPenner**
DoughnutChart: Fixes for code style and some properties. (See commits for details).

Other charts combined: Made `Data` a `List<double>`: Fixes https://github.com/Joelius300/ChartJSBlazor/issues/20 with https://github.com/Joelius300/ChartJSBlazor/commit/b1ab4906077efaee7cbc8697e70f34b06913fec0.

### CODE REVIEW

**Review by Joelius300 — CHANGES_REQUESTED** [review]
Can I assume that you thoroughly looked through [the page of this chart](https://www.chartjs.org/docs/latest/charts/doughnut.html)?  
You should always do that when reworking a chart since there are sometimes properties that could go forgotten and there's also where you find the descriptions for the summaries.

 - Put usings outside of namespace as mentioned in the [coding conventions](https://github.com/Joelius300/ChartJSBlazor/issues/22).

 - Circumferences -> Circumference ([see here](https://www.chartjs.org/docs/latest/charts/doughnut.html#config-options))
Good catch!

 - We don't need a `DoughnutTitle`. Just use `OptionsTitle`. Maybe we can put that into `ChartConfigBase`; Doesn't every chart have a title?

 - [This commit](https://github.com/Joelius300/ChartJSBlazor/pull/23/commits/d53e22924a65b0da96fef3720ba3d1994912e530):  
You should put `<see cref="ChartTypes.Doughnut"/>` there instead of just "Doughnut" or Doughnut. 
They don't need to know the string value, only chart.js does.

 - `DoughnutDataset.Data` (and basically every other `Data` property of reworked datasets) is supposed to be readonly and never null. 
It's always required so null doesn't make any sense (that's also why `DoughnutData.Labels` is readonly and never null. `LineChartData.Labels` is not required however so it's not readonly). You can still add and remove Data so it doesn't have to have a setter.  
You should remove that setter. Keep that also in mind for other charts if you're going to rework any.

 - Kind of connected to the last point. You changed the `Data` to `List<double>` even for datasets you're not reworking.  
Since this is a really nice thing to have and it's bad that it wasn't like that before, it's okay. But please don't apply such changes to charts you're not currently reworking.

Otherwise it seems good.   
As mentioned in the [coding conventions](https://github.com/Joelius300/ChartJSBlazor/issues/22) 
(after my edit), _Gets or sets_ is absolutely fine if you still take in account the description offered by chart.js.

Thanks for helping me :)  
After those changes, I'll merge it into a new branch, do anything left over (if necessary) and merge into master.

**Comment by SeppPenner** [comment]
Sure, I will try to add the changes soon. Thank you for the review.

**Comment by SeppPenner** [comment]
> Can I assume that you thoroughly looked through the page of this chart?

Now I have read through it. Seems like there have been some other issues (e.g. missing `Weight` and `BorderAlign`).

- [x] Put usings outside of namespace as mentioned in the coding conventions.
- [x] Circumferences -> Circumference
- [x] Doesn't every chart have a title? --> I would say yes: https://www.chartjs.org/docs/latest/configuration/title.html, I will open a new issue for that as it might impact other charts as well (Don't want to do it in this pull request.). Check https://github.com/Joelius300/ChartJSBlazor/issues/25.
- [x] You should put `<see cref="ChartTypes.Doughnut"/>` there instead of just "Doughnut" or Doughnut.
- [x] DoughnutDataset.Data (and basically every other Data property of reworked datasets) is supposed to be readonly and never null.

> Kind of connected to the last point. You changed the Data to List<double> even for datasets you're not reworking.
Since this is a really nice thing to have and it's bad that it wasn't like that before, it's okay. But please don't apply such changes to charts you're not currently reworking.

Sorry for that. I should have created a seperate issue for that. It was just so important for me that I decided to add it here already.

Todos (I don't really know if this is needed @Joelius300 ):
Check https://github.com/Joelius300/ChartJSBlazor/issues/31.

**Comment by SeppPenner** [comment]
From https://github.com/Joelius300/ChartJSBlazor/pull/30:
- [x] Rename DoughnutAnimation to PieAnimation
- [x] Update example for readonly List<double>
- [x] Optional bool parameter for options to switch between doughnut and pie, check https://github.com/Joelius300/ChartJSBlazor/issues/29#issuecomment-519171762
- [x] Checked and reworked explicit default values

**Comment by SeppPenner** [comment]
Todos (From before):
Check this issue: https://github.com/Joelius300/ChartJSBlazor/issues/31

**Comment by SeppPenner** [comment]
As this one is really getting big, I would recommend to merge it now (If you don't see any issues anymore) and provide further fixes in other pull requests.

**Comment by SeppPenner** [comment]
Just for reference, `borderColor` and `backgroundColor` need to be `string[]` in our case, `borderWidth` is a `int[]`. The same applies for `hoverBackgroundColor`, `hoverBorderColor` and `hoverBorderWidth`

Check https://github.com/chartjs/Chart.js/issues/6440, https://github.com/chartjs/Chart.js/issues/6442,
https://github.com/chartjs/Chart.js/issues/6444, https://github.com/chartjs/Chart.js/issues/6446 and https://jsfiddle.net/38shmLt1/3/.

**Comment by SeppPenner** [comment]
From https://jsfiddle.net/38shmLt1/3/:

- [x] The label is not needed as it doesn't have an impact at all.
- [x] Updated the data types for all mentioned above (https://github.com/Joelius300/ChartJSBlazor/pull/23#issuecomment-519426294) to be readonly lists.

**Comment by SeppPenner** [comment]
- [x] Added doughnut chart again because it causes problems with the chart type: https://github.com/Joelius300/ChartJSBlazor/issues/31#issuecomment-519455284
- [x] Renamed `PieAnimation` to `PieDoughnutAnimation` because it's used in both.
- [x] Fixed examples, added doughnut chart example.

**Comment by SeppPenner** [comment]
- [x] Added comment why the chart type is needed in the dataset.

**Comment by SeppPenner** [comment]
@Joelius300 What do you think here: Do we need any further changes? I would really like this one to be merged because it's getting way to big alreay...

**Comment by Joelius300** [comment]
Okay so first of all, yes I will merge this now but I will look into some things directly after merging.  

- We need to mention `ColorUtil` in `PieChartDataset.BackgroundColor` (and potentially other places it was forgotten)

- Good idea: Using getters and setters to set the Cutoutpercent. I think we can keep that (not 100% sure yet, see comment about the summary below) however I think we should remove the bool and just put `get => CutoutPercent > 0`.  
Also the summary has to be modified. It doesn't signal that it just changes the `CutoutPercent` but instead it seems like this is an independant property if it really is the complete opposite. That's also why I think the constructor would be a better choice since you can always change the CutoutPercent later if you wanted to.

- For the change from `string` to `string[]`, etc.. 
  - For the colors this 100% makes sense. I'm not so sure about the `BorderWidth`s though. First of all, since c# is strongly typed the user **has to** use a collection there. Again for the colors this only makes sense but when do you need to have different `BorderWidth`s for different arcs? 
I don't think that's going to be used really and if necessary we can just implement a wrapper which allows both an array or a single value (I can do that, that's easy).  
I opt to change that back to `int` for the `BorderWidth`s and open an issue where we discuss if we need/want a wrapper for values like this (I think there are other places this could be used as well).  

  - Also we **really** need to mention [indexable-options](https://www.chartjs.org/docs/latest/general/options.html#indexable-options) in the summary and in our wiki, otherwise noone will understand those `string[]`.

  - Last thing here, these don't need to be readonly since they can be null. The defaults of chart.js will be used. Readonly should only be used when the user is only allowed to modify the value. Here it's completely legitimate to set it to null.

- Doughnut chart revival. Now it's completely back which doesn't make any sense. If it doesn't work with only pie-chart we will just use a `DoughnutConfig` but all the options and data will be `PieData`. Otherwise we have way too much unnecessary redundancy.

**Comment by SeppPenner** [comment]
I will move this to seperate issues to make tracking easier:

* We need to mention ColorUtil: https://github.com/Joelius300/ChartJSBlazor/issues/42
* Good idea: Using getters and setters to set the Cutoutpercent: https://github.com/Joelius300/ChartJSBlazor/issues/43
* For the change from string to string[], etc..: https://github.com/Joelius300/ChartJSBlazor/issues/44
* Doughnut chart revival: Discussion here: https://github.com/Joelius300/ChartJSBlazor/issues/40

**Pull request merged**
